version: 2.0
jobs:
  build:
    docker:
      - image: circleci/python:2.7 
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            pip install --user -r requirements.txt
            python tests.py  
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
  dockerize:
    machine: true
    steps:
      - checkout
     # Login to docker 2
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

     # build the application image
      - run: docker build -t $DOCKER_USER/runleopard:$CIRCLE_SHA1 .

     # deploy the image
      - run: docker push $DOCKER_USER/runleopard:$CIRCLE_SHA1


